|BUILD CONFIGURATION| [Linux] Each file is checked for the return status, if it is not a success [0]         value, then a value of 1 will be returned, the build process wil stop 		and the output will be presented to the terminal

diff --git a/Source/Linux/Makefile b/Source/Linux/Makefile
--- a/Source/Linux/Makefile
+++ b/Source/Linux/Makefile
@@ -137,8 +137,19 @@ $(TARGET): $(OBJS)
 %.o: %.cpp
 	@printf "Compiling: $<... "
 	@$(CPP) -MMD -MP -MF $(OBJSDIR)/$*.d $(CPPFLAGS) $(SYSIPATH) $< \
-	-o $(OBJSDIR)/$@ > $(OBJSDIR)/$*.msgs 2>&1
-	@printf "[OK]\n"
+	-o $(OBJSDIR)/$@ 2> $(OBJSDIR)/$*.msgs;\
+	RETVAL=$$?;\
+	if [[ $$RETVAL == 0 ]]; then\
+		printf "[OK]\n";\
+	fi;\
+	if [[ $$RETVAL != 0 ]]; then\
+		printf "\n\n%s" "----------------------------------- ERROR ---------";\
+		printf "%s\n" "----------------------------------";\
+		cat $(OBJSDIR)/$*.msgs;\
+		printf "%s" "-------------------------------------------------------";\
+		printf "%s\n\n" "------------------------";\
+		exit 1;\
+	fi
 
 DEPENDS	:= $(OBJFILES:.o=.d)
 
